-- =========================================================
-- 기존 테이블 초기화
-- =========================================================
BEGIN
   FOR cur_rec IN (SELECT table_name FROM user_tables) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || cur_rec.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

-- =========================================================
-- 테이블 및 컬럼 정의
-- =========================================================

-- 1. 회원 및 보안 도메인
CREATE TABLE members (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    phone VARCHAR2(50),
    age_range VARCHAR2(50),
    job_type VARCHAR2(100),
    purpose_id NUMBER,

    is_job_recommend_enabled NUMBER(1) DEFAULT 1,

    role VARCHAR2(20) DEFAULT 'ROLE_USER',
    status VARCHAR2(20) DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    
    last_login_at TIMESTAMP,

    CONSTRAINT chk_members_job_recommend CHECK (is_job_recommend_enabled IN (0,1)),
    CONSTRAINT chk_members_role CHECK (role IN ('ROLE_USER','ROLE_ADMIN')),
    CONSTRAINT chk_members_status CHECK (
        status IN ('ACTIVE', 'WITHDRAWN', 'SUSPENDED', 'DORMANT')
    )
);

-- 1-2. 비밀번호 재설정 토큰
CREATE TABLE password_reset_tokens (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    token VARCHAR2(255) NOT NULL,
    expiry_date TIMESTAMP NOT NULL,

    CONSTRAINT fk_password_reset_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
        ON DELETE CASCADE
);

-- 2. 웹 접근성 설정
CREATE TABLE accessibility_settings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER UNIQUE NOT NULL,

    font_size_step NUMBER DEFAULT 1,
    high_contrast_enabled NUMBER(1) DEFAULT 0,
    screen_reader_optimized NUMBER(1) DEFAULT 0,

    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_accessibility_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
);

-- 3. 배송지 및 주문 정보
CREATE TABLE addresses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER,

    address_name VARCHAR2(100),
    zip_code VARCHAR2(20),
    base_address VARCHAR2(255),
    detail_address VARCHAR2(255),

    receiver_name VARCHAR2(100),
    receiver_phone VARCHAR2(50),

    is_default NUMBER(1) DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_addresses_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
);

-- 4-1. 카테고리
CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR2(100),

    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 4. 상품 및 메타 데이터
CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    category_id NUMBER,

    name VARCHAR2(255) NOT NULL,
    price NUMBER NOT NULL,
    discount_rate NUMBER DEFAULT 0 NOT NULL,
    delivery_fee NUMBER NOT NULL,

    stock_quantity NUMBER DEFAULT 0,

    short_description VARCHAR2(500),
    description CLOB,

    brand VARCHAR2(100),
    origin VARCHAR2(100),

    spec_info CLOB,

    alt_text CLOB,

    weight_score NUMBER DEFAULT 0,
    recent_score NUMBER DEFAULT 0,

    status VARCHAR2(20) DEFAULT 'ON_SALE',

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id),

    CONSTRAINT chk_products_status CHECK (
        status IN (
            'ON_SALE',
            'DISCONTINUED',
            'SOLD_OUT',
            'VEILED',
            'WAITING',
            'DELETED'
        )
    )
);

-- 4-2. 상품 이미지
CREATE TABLE product_images (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id NUMBER,

    image_url VARCHAR2(500),

    is_main NUMBER(1) DEFAULT 0,

    CONSTRAINT fk_product_images_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
);

-- 4-3. 메타 태그
CREATE TABLE meta_tags (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR2(100) NOT NULL,

    type VARCHAR2(30) NOT NULL,

    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT chk_meta_tags_type CHECK (
        type IN (
            'CATEGORY',
            'SEASONAL',
            'PURPOSE',
            'MERCHANDISING',
            'OCCUPATION',
            'AGE_PREFERENCE',
            'POPULARITY',
            'RELEASE_OR_UPDATE'
        )
    ),

    CONSTRAINT chk_meta_tags_status CHECK (
        status IN ('ACTIVE','DELETED')
    ),
    CONSTRAINT uq_meta_tags_name_type UNIQUE (name, type)
);

-- 4-4. 상품-메타태그 매핑
CREATE TABLE product_meta_tags (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id NUMBER NOT NULL,
    meta_tag_id NUMBER NOT NULL,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_product_meta_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT fk_product_meta_tag
        FOREIGN KEY (meta_tag_id)
        REFERENCES meta_tags(id),

    CONSTRAINT uq_product_meta
        UNIQUE (product_id, meta_tag_id)
);

-- 4-5. 유저별 취향 가중치 프로필
CREATE TABLE member_tag_weights (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id NUMBER NOT NULL,
    meta_tag_id NUMBER NOT NULL,

    profile_score NUMBER DEFAULT 0,
    weight_score NUMBER DEFAULT 0,
    effective_score NUMBER DEFAULT 0,

    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_member_tag_weights_member
        FOREIGN KEY (member_id)
        REFERENCES members(id),

    CONSTRAINT fk_member_tag_weights_tag
        FOREIGN KEY (meta_tag_id)
        REFERENCES meta_tags(id),

    CONSTRAINT uq_member_tag_weights
        UNIQUE (member_id, meta_tag_id)
);

-- 5. 추천 로직 및 활동 데이터
CREATE TABLE metatag_weight_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id NUMBER NOT NULL,
    metatag_id NUMBER NOT NULL,

    action_type VARCHAR2(30),

    applied_weight NUMBER,

    reference_id NUMBER,

    event_timestamp TIMESTAMP,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE product_weight_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,

    action_type VARCHAR2(30),

    applied_weight NUMBER,

    reference_id NUMBER,

    event_timestamp TIMESTAMP,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 5-1. 북마크
CREATE TABLE bookmarks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_bookmarks_member
        FOREIGN KEY (member_id)
        REFERENCES members(id),

    CONSTRAINT fk_bookmarks_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT uq_bookmark_member_product
        UNIQUE (member_id, product_id)
);

-- 6. 주문 및 결제
CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id NUMBER NOT NULL,
    address_id NUMBER,

    receiver_name VARCHAR2(100),
    receiver_phone VARCHAR2(50),

    delivery_address VARCHAR2(500),

    request_message VARCHAR2(500),

    total_amount NUMBER NOT NULL,
    delivery_fee NUMBER NOT NULL,

    payment_method VARCHAR2(50),

    status VARCHAR2(30) DEFAULT 'PENDING',

    tracking_number VARCHAR2(100),

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_orders_member
        FOREIGN KEY (member_id)
        REFERENCES members(id),

    CONSTRAINT fk_orders_address
        FOREIGN KEY (address_id)
        REFERENCES addresses(id),

    CONSTRAINT chk_orders_status CHECK (
        status IN (
            'PENDING',
            'PAID',
            'SHIPPING',
            'DELIVERED',
            'CANCELLED'
        )
    ),

    CONSTRAINT chk_orders_payment_method CHECK (
        payment_method IN (
            'CASH',
            'CARD',
            'MOBILE_PAY'
        )
    )
);

-- 6-1. 주문 아이템
CREATE TABLE order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id NUMBER NOT NULL,

    source VARCHAR2(20) DEFAULT 'INTERNAL' NOT NULL,

    product_id NUMBER,

    naver_product_id VARCHAR2(100),

    product_name VARCHAR2(255),

    image_url VARCHAR2(500),

    category VARCHAR2(100),

    description CLOB,

    quantity NUMBER,

    price_at_order NUMBER,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id),

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT chk_order_items_source CHECK (
        source IN ('INTERNAL','NAVER')
    )
);

-- 6-2. 결제
CREATE TABLE payments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id NUMBER UNIQUE NOT NULL,

    payment_key VARCHAR2(255) UNIQUE,

    payment_method VARCHAR2(100),

    amount NUMBER,

    status VARCHAR2(50),

    approved_at TIMESTAMP,

    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id),

    CONSTRAINT chk_payments_method CHECK (
        payment_method IN (
            'CASH',
            'CARD',
            'MOBILE_PAY'
        )
    ),

    CONSTRAINT chk_payments_status CHECK (
        status IN (
            'PENDING',
            'PROCESSING',
            'CANCELED',
            'COMPLETED',
            'FAILED'
        )
    )
);

-- 6-3. 장바구니
CREATE TABLE cart_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id NUMBER NOT NULL,

    source VARCHAR2(20) DEFAULT 'INTERNAL' NOT NULL,

    product_id NUMBER,

    naver_product_id VARCHAR2(100),

    product_name VARCHAR2(255),

    image_url VARCHAR2(500),

    price NUMBER,

    quantity NUMBER,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_cart_member
        FOREIGN KEY (member_id)
        REFERENCES members(id),

    CONSTRAINT fk_cart_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT chk_cart_items_source CHECK (
        source IN ('INTERNAL','NAVER')
    )
);

-- 7. 리뷰 및 소통
CREATE TABLE reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id NUMBER NOT NULL,

    product_id NUMBER,

    order_item_id NUMBER UNIQUE NOT NULL,

    rating NUMBER NOT NULL,

    content CLOB NOT NULL,

    image_url VARCHAR2(500),

    status VARCHAR2(20) DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_reviews_member
        FOREIGN KEY (member_id)
        REFERENCES members(id),

    CONSTRAINT fk_reviews_product
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT fk_reviews_order_item
        FOREIGN KEY (order_item_id)
        REFERENCES order_items(id),

    CONSTRAINT chk_reviews_status CHECK (
        status IN ('ACTIVE','HIDDEN','DELETED')
    )
);

-- 8. 검색 및 인기 검색어
CREATE TABLE search_keywords (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    keyword VARCHAR2(100) UNIQUE NOT NULL,

    search_count NUMBER DEFAULT 1 NOT NULL,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    updated_at TIMESTAMP
);

-- 9. 고객지원 데이터
CREATE TABLE faqs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR2(100) NOT NULL,                    
    title CLOB NOT NULL,                              
    content CLOB NOT NULL,                            
    status VARCHAR2(20) DEFAULT 'ACTIVE',            
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,       
    
    CONSTRAINT chk_faqs_status CHECK (status IN ('ACTIVE', 'DELETED'))
);

CREATE TABLE qnas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    title VARCHAR2(255),
    content CLOB,
    answer CLOB,
    status VARCHAR2(50) DEFAULT 'WAITING',
    
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,
    answered_at TIMESTAMP,                              

    CONSTRAINT fk_qnas_member
        FOREIGN KEY (member_id)
        REFERENCES members(id)
);

-- =========================================================
-- FK 추가
-- =========================================================

ALTER TABLE members
ADD CONSTRAINT fk_members_purpose
FOREIGN KEY (purpose_id)
REFERENCES meta_tags(id);

ALTER TABLE metatag_weight_logs
ADD CONSTRAINT fk_metatag_logs_member
FOREIGN KEY (member_id)
REFERENCES members(id);

ALTER TABLE metatag_weight_logs
ADD CONSTRAINT fk_metatag_logs_tag
FOREIGN KEY (metatag_id)
REFERENCES meta_tags(id);

ALTER TABLE product_weight_logs
ADD CONSTRAINT fk_product_logs_member
FOREIGN KEY (member_id)
REFERENCES members(id);

ALTER TABLE product_weight_logs
ADD CONSTRAINT fk_product_logs_product
FOREIGN KEY (product_id)
REFERENCES products(id);


-- =========================================================
--  메타 태그 초기 데이터
-- =========================================================

-- ① CATEGORY 관련 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (1, '건강', 'CATEGORY', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (2, '교육', 'CATEGORY', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (3, '여행', 'CATEGORY', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (4, '선물', 'CATEGORY', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (5, '가전', 'CATEGORY', 'ACTIVE');

-- ② PURPOSE 관련 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (6, '나를 위한 구매', 'PURPOSE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (7, '선물용', 'PURPOSE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (8, '가족/아이', 'PURPOSE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (9, '업무/직장', 'PURPOSE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (10, '취미/여가', 'PURPOSE', 'ACTIVE');

-- ③ MERCHANDISING 관련 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (11, '가성비', 'MERCHANDISING', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (12, '고품질', 'MERCHANDISING', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (13, '실용적', 'MERCHANDISING', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (14, '트렌디', 'MERCHANDISING', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (15, '친환경', 'MERCHANDISING', 'ACTIVE');

-- ③ OCCUPATION(JOB_TYPE/직종) 관련 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (16, '사무', 'OCCUPATION', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (17, '영업', 'OCCUPATION', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (18, '현장', 'OCCUPATION', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (19, '의료', 'OCCUPATION', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (20, '교육', 'OCCUPATION', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (21, '기타', 'OCCUPATION', 'ACTIVE');

-- ④ 연령대(AGE_PREFERENCE) 관련 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (22, '영유아', 'AGE_PREFERENCE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (23, '10대', 'AGE_PREFERENCE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (24, '20대', 'AGE_PREFERENCE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (25, '30대', 'AGE_PREFERENCE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (26, '40대', 'AGE_PREFERENCE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (27, '50대', 'AGE_PREFERENCE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (28, '60대 이상', 'AGE_PREFERENCE', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (29, '전연령', 'AGE_PREFERENCE', 'ACTIVE');

-- ⑤ SEASONAL(계절 별) 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (30, '초봄', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (31, '봄', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (32, '여름', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (33, '초가을', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (34, '가을', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (35, '초겨울', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (36, '겨울', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (37, '장마', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (38, '연말', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (39, '연초', 'SEASONAL', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (40, '명절', 'SEASONAL', 'ACTIVE');


-- ⑥ POPULARITY 관련 태그
INSERT INTO meta_tags (id, name, type, status)
VALUES (41, '인기 상품', 'POPULARITY', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (42, '스테디셀러', 'POPULARITY', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (43, '주목 상품', 'POPULARITY', 'ACTIVE');

INSERT INTO meta_tags (id, name, type, status)
VALUES (44, '특가 세일', 'POPULARITY', 'ACTIVE');



-- ⑦ CATEGORY 테이블 초기 데이터
INSERT INTO categories(id, name)
VALUES (1, '건강');

INSERT INTO categories(id, name)
VALUES (2, '교육');

INSERT INTO categories(id, name)
VALUES (3, '여행');

INSERT INTO categories(id, name)
VALUES (4, '선물');

INSERT INTO categories(id, name)
VALUES (5, '가전');


ALTER TABLE categories MODIFY (
  id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)
);

-- 100번부터 meta_tags 등록이 가능하도록 처리(스키마와 겹치지 않도록)
ALTER TABLE meta_tags MODIFY (
  id GENERATED BY DEFAULT AS IDENTITY (START WITH 100)
);


COMMIT;