-- =========================================================
-- 기존 테이블 초기화
-- =========================================================
BEGIN
   FOR cur_rec IN (SELECT table_name FROM user_tables) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || cur_rec.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

-- =========================================================
-- 테이블 및 컬럼 정의 (수정일시, 연락처, 토큰 완전 포함)
-- =========================================================

-- 1. 회원 및 보안 도메인
CREATE TABLE members (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    phone VARCHAR2(50), 
    age_range VARCHAR2(50),
    job_type VARCHAR2(100),
    purpose_id NUMBER, 

    is_job_recommend_enabled NUMBER(1) DEFAULT 1,

    role VARCHAR2(20) DEFAULT 'ROLE_USER',
    status VARCHAR2(20) DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT chk_members_job_recommend CHECK (is_job_recommend_enabled IN (0,1)),
    CONSTRAINT chk_members_role CHECK (role IN ('ROLE_USER','ROLE_ADMIN')),
    CONSTRAINT chk_members_status CHECK (status IN ('ACTIVE', 'WITHDRAWN', 'SUSPENDED', 'DORMANT'))
);

-- 1-2. 비밀번호 재설정 토큰 테이블
CREATE TABLE password_reset_tokens (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    token VARCHAR2(255) NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    
    CONSTRAINT fk_password_reset_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE
);

-- 2. 웹 접근성 설정
CREATE TABLE accessibility_settings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER UNIQUE NOT NULL,

    font_size_step NUMBER DEFAULT 1,
    high_contrast_enabled NUMBER(1) DEFAULT 0,
    screen_reader_optimized NUMBER(1) DEFAULT 0,

    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_accessibility_member FOREIGN KEY (member_id) REFERENCES members(id)
);

-- 3. 배송지 및 주문 정보
CREATE TABLE addresses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,

    address_name VARCHAR2(100),
    zip_code VARCHAR2(20),
    base_address VARCHAR2(255),
    detail_address VARCHAR2(255),

    receiver_name VARCHAR2(100),
    receiver_phone VARCHAR2(50),

    is_default NUMBER(1) DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_addresses_member FOREIGN KEY (member_id) REFERENCES members(id)
);

-- 4-1. 카테고리
CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 4. 상품 및 테마/메타 데이터
CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id NUMBER,

    name VARCHAR2(255) NOT NULL,
    price NUMBER NOT NULL,
    delivery_fee NUMBER NOT NULL,

    stock_quantity NUMBER DEFAULT 0,

    short_description VARCHAR2(500),
    description CLOB,
    brand VARCHAR2(100),
    origin VARCHAR2(100),
    spec_info CLOB,

    alt_text VARCHAR2(255),

    weight_score NUMBER DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'ON_SALE',

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT chk_products_status CHECK (status IN ('ON_SALE', 'DISCONTINUED', 'SOLD_OUT', 'VEILED', 'WAITING'))
);

-- 4-2. 상품 이미지
CREATE TABLE product_images (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,

    image_url VARCHAR2(500) NOT NULL,
    is_main NUMBER(1) DEFAULT 0,

    CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES products(id)
);

-- 4-3. 메타 태그
CREATE TABLE meta_tags (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE NOT NULL,
    type VARCHAR2(30) NOT NULL,
    meta_tag_status VARCHAR2(20) DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT chk_meta_tags_type CHECK (
        type IN (
            'CATEGORY', 'PURPOSE', 'MERCHANDISING', 'OCCUPATION', 'AGE_PREFERENCE', 'POPULARITY', 'RELEASE_OR_UPDATE'
        )
    ),
    CONSTRAINT chk_meta_tags_status CHECK (meta_tag_status IN ('ACTIVE','DELETED'))
);

-- 4-4. 상품-메타태그 매핑
CREATE TABLE product_meta_tags (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    meta_tag_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_product_meta_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_product_meta_tag FOREIGN KEY (meta_tag_id) REFERENCES meta_tags(id),
    CONSTRAINT uq_product_meta UNIQUE (product_id, meta_tag_id)
);

-- 4-5. 유저별 취향 가중치 프로필
CREATE TABLE member_tag_weights (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    meta_tag_id NUMBER NOT NULL,
    weight_score NUMBER DEFAULT 0,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_member_tag_weights_member FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT fk_member_tag_weights_tag FOREIGN KEY (meta_tag_id) REFERENCES meta_tags(id),
    CONSTRAINT uq_member_tag_weights UNIQUE (member_id, meta_tag_id)
);

-- 5. 추천 로직 및 활동 데이터
CREATE TABLE metatag_weight_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    metatag_id NUMBER NOT NULL,
    action_type VARCHAR2(50),
    applied_weight NUMBER,
    reference_id NUMBER,
    event_timestamp TIMESTAMP,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    status VARCHAR2(20)
);

CREATE TABLE product_weight_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    action_type VARCHAR2(50),
    applied_weight NUMBER,
    reference_id NUMBER,
    event_timestamp TIMESTAMP,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    status VARCHAR2(20)
);

-- 5-1. 북마크
CREATE TABLE bookmarks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_bookmarks_member FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT fk_bookmarks_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT uq_bookmark_member_product UNIQUE (member_id, product_id)
);

-- 6. 주문 및 결제
CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    address_id NUMBER,
    total_amount NUMBER NOT NULL,
    delivery_fee NUMBER NOT NULL,

    status VARCHAR2(50) DEFAULT 'PENDING',
    tracking_number VARCHAR2(100),

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_orders_member FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT fk_orders_address FOREIGN KEY (address_id) REFERENCES addresses(id),
    CONSTRAINT chk_orders_status CHECK (
        status IN (
            'PENDING', 'PROCESSING', 'CANCELED', 'COMPLETED', 'FAILED',
            'BEFORE_SHIPMENT', 'IN_TRANSIT', 'DELIVERED',
            'EXCHANGE_REQUESTED', 'RETURN_REQUESTED', 'CANCEL_REQUESTED', 'REJECTED', 'IN_PROGRESS'
        )
    )
);

-- 6-1. order_items
CREATE TABLE order_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    price_at_order NUMBER NOT NULL,

    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id)
);

-- 6-2. payments
CREATE TABLE payments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER UNIQUE NOT NULL,
    payment_key VARCHAR2(255) UNIQUE,

    payment_method VARCHAR2(100),
    amount NUMBER,
    status VARCHAR2(50),

    approved_at TIMESTAMP,

    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT chk_payments_method CHECK (payment_method IN ('CASH', 'CARD', 'MOBILE_PAY')),
    CONSTRAINT chk_payments_status CHECK (status IN ('PENDING', 'PROCESSING', 'CANCELED', 'COMPLETED', 'FAILED'))
);

-- 6-3. cart_items
CREATE TABLE cart_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER DEFAULT 1,

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_cart_member FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT uq_cart_member_product UNIQUE (member_id, product_id)
);

-- 7. 리뷰 및 소통
CREATE TABLE reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    order_item_id NUMBER UNIQUE,

    rating NUMBER,
    content CLOB,
    image_url VARCHAR2(500),

    status VARCHAR2(30) DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_reviews_member FOREIGN KEY (member_id) REFERENCES members(id),
    CONSTRAINT fk_reviews_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id)
);

-- 8. 고객지원 데이터
CREATE TABLE faqs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question CLOB NOT NULL,
    answer CLOB NOT NULL,
    category VARCHAR2(100)
);

-- 8-1. qnas
CREATE TABLE qnas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id NUMBER NOT NULL,
    title VARCHAR2(255),
    content CLOB,
    answer CLOB,
    status VARCHAR2(50) DEFAULT 'WAITING',

    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT fk_qnas_member FOREIGN KEY (member_id) REFERENCES members(id)
);

ALTER TABLE members ADD CONSTRAINT fk_members_purpose FOREIGN KEY (purpose_id) REFERENCES meta_tags(id);
ALTER TABLE metatag_weight_logs ADD CONSTRAINT fk_metatag_logs_member FOREIGN KEY (member_id) REFERENCES members(id);
ALTER TABLE metatag_weight_logs ADD CONSTRAINT fk_metatag_logs_tag FOREIGN KEY (metatag_id) REFERENCES meta_tags(id);
ALTER TABLE product_weight_logs ADD CONSTRAINT fk_product_logs_member FOREIGN KEY (member_id) REFERENCES members(id);
ALTER TABLE product_weight_logs ADD CONSTRAINT fk_product_logs_product FOREIGN KEY (product_id) REFERENCES products(id);

-- =========================================================
--  메타 태그 초기 데이터
-- =========================================================

-- ① CATEGORY 관련 태그
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (1, '건강', 'CATEGORY', 'ACTIVE');
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (2, '교육', 'CATEGORY', 'ACTIVE');
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (3, '여행', 'CATEGORY', 'ACTIVE');
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (4, '선물', 'CATEGORY', 'ACTIVE');
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (5, '가전', 'CATEGORY', 'ACTIVE');

-- ② PURPOSE 관련 태그
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (6, '나를 위한 구매', 'PURPOSE', 'ACTIVE');
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (7, '선물용', 'PURPOSE', 'ACTIVE');
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (8, '가족/아이', 'PURPOSE', 'ACTIVE');
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (9, '업무/직장', 'PURPOSE', 'ACTIVE');
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (10, '취미/여가', 'PURPOSE', 'ACTIVE');

-- ③ MERCHANDISING 관련 태그
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (11, '가성비', 'MERCHANDISING', 'ACTIVE');
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (12, '고품질', 'MERCHANDISING', 'ACTIVE');
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (13, '실용적', 'MERCHANDISING', 'ACTIVE');
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (14, '트렌디', 'MERCHANDISING', 'ACTIVE');
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (15, '친환경', 'MERCHANDISING', 'ACTIVE');

-- ④ 마케팅 보조용 시스템 태그 
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (41, '인기 상품', 'POPULARITY', 'ACTIVE');
INSERT INTO meta_tags (id, name, type, meta_tag_status) VALUES (44, '특가 세일', 'POPULARITY', 'ACTIVE'); 

-- ⑤ 5대 메인 서비스 카테고리 데이터
INSERT INTO categories(id, name) VALUES(1, '건강');
INSERT INTO categories(id, name) VALUES(2, '교육');
INSERT INTO categories(id, name) VALUES(3, '여행');
INSERT INTO categories(id, name) VALUES(4, '선물');
INSERT INTO categories(id, name) VALUES(5, '가전');

ALTER TABLE categories MODIFY (
  id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)
);

COMMIT;